# Generated by Django 3.2 on 2022-12-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('review_text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('stockitem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.stockitem')),
            ],
        ),
    ]
